#pragma once

namespace tateyama::authentication::crypto {

static const char token[] = {"eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJyZWZyZXNoIiwiYXVkIjoiYXV0aGVudGljYXRpb24tbWFuYWdlciIsInRzdXJ1Z2kvYXV0aC9uYW1lIjoidXNlciIsImlzcyI6ImF1dGhlbnRpY2F0aW9uLW1hbmFnZXIiLCJleHAiOjE3NDk4MjAzODgsImlhdCI6MTc0OTczMzk4OCwianRpIjoiMjJhMWMxZTQtY2IyZC00ZWRiLTk5ZmItYTg1YWYwNWU4ZTA2In0.TZVHZTPv8ojKot8mIq5R_khikX8dMUTJEJGDMkmnuoqcoN4-PYJZPjJU5EUh1-qk9WrIhMfzTLHcMneMNb4_It1RDUPd4DXScvOK9annT7xf8PZ2xIaGdui3Uyw1MSfRIgdIZMuxeuRRGgmBZTpKGPDNQkCGnVpxVIH0THC6km3IacitJ2SmOcUmrdmUVdbSmtK6xgBgG2IMA-CkDYza2wyXl212kpoecvm1FWDqC3iAkc-NOgyEnKYNlh44bp44_q5NMdtBemfb3Y_kQ2Xn8tYM0LFpIewxGo29ImgNg2RjmHNPNvhXZp0XybtpE-7JFhizdWzBM7c5UK_pFfFcyQ"};

} // namespace tateyama::authentication::crypto
