name: Tateyama-bootstrap-CI

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      os:
        type: string
        default: 'ubuntu-22.04'

jobs:
  Build:
    runs-on: [self-hosted, docker]
    permissions:
      checks: write
    timeout-minutes: 30
    container:
      image: ghcr.io/project-tsurugi/tsurugi-ci:${{ inputs.os || 'ubuntu-22.04' }}
      volumes:
        - ${{ vars.ccache_dir }}:${{ vars.ccache_dir }}
    defaults:
      run:
        shell: bash
    env:
      CCACHE_CONFIGPATH: ${{ vars.ccache_dir }}/ccache.conf
      CCACHE_DIR: ${{ vars.ccache_dir }}/${{ inputs.os || 'ubuntu-22.04' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install_Dependencies
        uses: ./.github/actions/install-dependencies
        with:
          sharksfin-implementation: shirakami

      - name: Install_mpdecimal
        if: inputs.os == 'ubuntu-24.04'
        run: |
          mkdir build-mpdecimal
          cd build-mpdecimal
          curl -OL https://www.bytereef.org/software/mpdecimal/releases/mpdecimal-2.5.1.tar.gz
          tar xf mpdecimal-2.5.1.tar.gz
          cd mpdecimal-2.5.1
          ./configure --prefix="${GITHUB_WORKSPACE}/.local"
          make -j8
          make install
          cd ../..
          rm -fr build-mpdecimal;
        shell: bash

      - name: CMake_Install
        run: |
          rm -rf build
          mkdir build
          cd build
          cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DSHARKSFIN_IMPLEMENTATION=shirakami -DOGAWAYAMA=ON -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_INSTALL_PREFIX=${GITHUB_WORKSPACE}/.local ..
          cmake --build . --target install --clean-first

      - name: CTest
        env:
          GTEST_OUTPUT: xml
          ASAN_OPTIONS: detect_stack_use_after_return=true
        run: |
          export PATH=$PATH:${GITHUB_WORKSPACE}/.local/bin
          cd build
          ctest --verbose

      - name: Verify
        uses: project-tsurugi/tsurugi-annotations-action@v1
        if: always()

  Analysis:
    runs-on: [self-hosted, docker]
    permissions:
      checks: write
    timeout-minutes: 30
    container:
      image: ghcr.io/project-tsurugi/tsurugi-ci:ubuntu-22.04
      volumes:
        - ${{ vars.ccache_dir }}:${{ vars.ccache_dir }}
    defaults:
      run:
        shell: bash
    env:
      CCACHE_CONFIGPATH: ${{ vars.ccache_dir }}/ccache.conf
      CCACHE_DIR: ${{ vars.ccache_dir }}/ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install_Dependencies
        uses: ./.github/actions/install-dependencies
        with:
          sharksfin-implementation: shirakami

      - name: CMake_Build
        run: |
          rm -rf build
          mkdir build
          cd build
          cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DSHARKSFIN_IMPLEMENTATION=shirakami -DOGAWAYAMA=ON -DCMAKE_PREFIX_PATH=${GITHUB_WORKSPACE}/.local -DCMAKE_EXPORT_COMPILE_COMMANDS=ON ..
          cmake --build . --target all --clean-first

      - name: Clang-Tidy
        run: |
          python tools/bin/run-clang-tidy.py -quiet -export-fixes=build/clang-tidy-fix.yaml -p build -extra-arg=-Wno-unknown-warning-option -header-filter=$(pwd)'/(include|src)/.*\.h$' $(pwd)'/src/.*' 2>&1 | awk '!a[$0]++{print > "build/clang-tidy.log"}'

      - name: Doxygen
        run: |
          cd build
          ninja doxygen 2> >(tee doxygen-error.log)

      - name: Verify
        uses: project-tsurugi/tsurugi-annotations-action@v1
        if: always()
